### ISSUE TITLE
при попытке отправить картинку на проверку ошибка

### ISSUE THREAD

**Issue by Armyanin** [Vitomed/Cats-vs-Dogs-Web-Flask-#1]
передаю файл с названием 2.jpg

FileNotFoundError: [Errno 2] No such file or directory: 'saveimages\\2.jpg'

**Comment by vitomed** [comment]
Добавил пустую директорию  saveimages в проект.  Решило ли это вашу проблему? 
У меня была та же ошибка, при отсутствии директории saveimages. Автоматически, она не создается при сохранении файла name.jpg. Когда есть saveimages в проекте и на том месте, где ее ищет Python, все должно работать.
